import {
  UserProfile,
  Opportunity,
  JobApplication,
  UserSkill,
  Experience,
  Education,
  Project,
  Certification,
  CareerResource,
  Language,
  AdminStats,
  PortfolioConfig,
  CVDocument,
  Notification,
  RoleSkillGap
} from '../types';

export const INITIAL_USER_TEDDY: UserProfile = {
  id: 'usr-teddy-001',
  email: 'teddy.mwangi@uonbi.ac.ke',
  fullName: 'Teddy Mwangi',
  headline: 'Junior Full-Stack Engineer & CS Graduate | Building with React, Node.js & Python',
  bio: 'Computer Science graduate from the University of Nairobi with passion for scalable web platforms, financial inclusion APIs, and mobile solutions in East Africa. Seeking full-time or high-impact graduate engineering roles.',
  location: 'Nairobi, Kenya',
  phone: '+254 712 345 678',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=300',
  role: 'graduate',
  profileStrength: 80,
  githubUrl: 'https://github.com/teddymwangi',
  linkedinUrl: 'https://linkedin.com/in/teddymwangi',
  portfolioUrl: 'https://careerlaunch.co.ke/u/teddymwangi',
  twitterUrl: 'https://x.com/teddymwangi_dev',
  createdAt: '2026-01-15T08:00:00Z',
  updatedAt: '2026-09-18T14:30:00Z',
};

export const INITIAL_USER_AMINA: UserProfile = {
  id: 'usr-amina-002',
  email: 'amina.wanjiku@studio.design',
  fullName: 'Amina Wanjiku',
  headline: 'Senior UI/UX & Product Designer | Fintech & Mobile Design Specialist',
  bio: 'Product designer with 4+ years creating accessible interfaces for mobile-first African products. Experienced with Figma, user research in informal retail markets, and design systems.',
  location: 'Nairobi, Kenya (Available Remote Pan-Africa)',
  phone: '+254 722 987 654',
  avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=300',
  role: 'freelancer',
  profileStrength: 95,
  githubUrl: 'https://github.com/aminadesign',
  linkedinUrl: 'https://linkedin.com/in/aminawanjiku',
  portfolioUrl: 'https://careerlaunch.co.ke/u/aminawanjiku',
  twitterUrl: 'https://x.com/amina_ux',
  createdAt: '2025-11-10T10:00:00Z',
  updatedAt: '2026-09-20T11:15:00Z',
};

export const INITIAL_USER_ADMIN: UserProfile = {
  id: 'usr-admin-003',
  email: 'admin@careerlaunch.co.ke',
  fullName: 'Sarah Kipchoge',
  headline: 'Platform Administrator & Talent Partnerships Director',
  bio: 'Overseeing corporate partnerships with tech hubs, universities, and enterprise recruiters across East and West Africa.',
  location: 'Nairobi, Kenya',
  phone: '+254 700 000 001',
  avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=300',
  role: 'admin',
  profileStrength: 100,
  createdAt: '2025-08-01T00:00:00Z',
  updatedAt: '2026-09-21T09:00:00Z',
};

export const INITIAL_SKILLS: UserSkill[] = [
  { id: 'sk-1', userId: 'usr-teddy-001', skillName: 'React & Next.js', category: 'Technical', proficiencyLevel: 'Advanced', yearsOfExperience: 2 },
  { id: 'sk-2', userId: 'usr-teddy-001', skillName: 'TypeScript', category: 'Technical', proficiencyLevel: 'Intermediate', yearsOfExperience: 1.5 },
  { id: 'sk-3', userId: 'usr-teddy-001', skillName: 'Node.js & Express', category: 'Technical', proficiencyLevel: 'Advanced', yearsOfExperience: 2 },
  { id: 'sk-4', userId: 'usr-teddy-001', skillName: 'Python & FastAPI', category: 'Technical', proficiencyLevel: 'Intermediate', yearsOfExperience: 1.5 },
  { id: 'sk-5', userId: 'usr-teddy-001', skillName: 'PostgreSQL / Supabase', category: 'Data & AI', proficiencyLevel: 'Intermediate', yearsOfExperience: 2 },
  { id: 'sk-6', userId: 'usr-teddy-001', skillName: 'Git & GitHub Workflows', category: 'Tools & Frameworks', proficiencyLevel: 'Advanced', yearsOfExperience: 3 },
  { id: 'sk-7', userId: 'usr-teddy-001', skillName: 'RESTful API Design', category: 'Technical', proficiencyLevel: 'Advanced', yearsOfExperience: 2 },
  { id: 'sk-8', userId: 'usr-teddy-001', skillName: 'Agile & Scrum Collaboration', category: 'Soft Skills', proficiencyLevel: 'Intermediate', yearsOfExperience: 1 },
];

export const INITIAL_EDUCATION: Education[] = [
  {
    id: 'edu-1',
    userId: 'usr-teddy-001',
    institution: 'University of Nairobi (Chiromo Campus)',
    degree: 'Bachelor of Science',
    fieldOfStudy: 'Computer Science',
    startDate: '2022-09-01',
    endDate: '2026-07-30',
    isCurrent: false,
    grade: 'First Class Honours',
    description: 'Specialized in Software Engineering, Distributed Systems, and Data Structures. Led the Google Developer Student Club (GDSC) chapter.',
  },
  {
    id: 'edu-2',
    userId: 'usr-teddy-001',
    institution: 'Moringa School',
    degree: 'Professional Certificate',
    fieldOfStudy: 'Full-Stack Software Development',
    startDate: '2023-01-10',
    endDate: '2023-06-25',
    isCurrent: false,
    grade: 'Distinction',
    description: 'Intensive 24-week immersive bootcamp covering modern web architecture, collaborative pair programming, and CI/CD pipelines.',
  },
];

export const INITIAL_EXPERIENCE: Experience[] = [
  {
    id: 'exp-1',
    userId: 'usr-teddy-001',
    company: 'Twiga Foods Tech Hub',
    position: 'Software Engineering Attachment / Intern',
    employmentType: 'Attachment',
    location: 'Nairobi, Kenya',
    startDate: '2025-05-01',
    endDate: '2025-08-31',
    isCurrent: false,
    description: 'Collaborated on vendor logistics dashboard using React and Python microservices. Integrated M-Pesa Daraja API for automated merchant settlements, processing over 12,000 daily transactions.',
  },
  {
    id: 'exp-2',
    userId: 'usr-teddy-001',
    company: 'Upwork Global / Freelance',
    position: 'Junior Web Developer',
    employmentType: 'Freelance',
    location: 'Remote (Kenya)',
    startDate: '2025-09-01',
    endDate: '',
    isCurrent: true,
    description: 'Built responsive client web applications, landing pages, and customized Supabase backends for SME clients across Kenya and UK.',
  },
];

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'proj-1',
    userId: 'usr-teddy-001',
    title: 'KilimoConnect - Smallholder Farmer Marketplace',
    description: 'PWA connecting dairy and avocado farmers in Central Kenya directly to urban bulk buyers. Features SMS USSD alerts, real-time pricing feeds, and M-Pesa escrow.',
    link: 'https://kilimoconnect-demo.co.ke',
    githubLink: 'https://github.com/teddymwangi/kilimoconnect',
    imageUrl: 'https://images.unsplash.com/photo-1595974482597-4b8da8879bc5?auto=format&fit=crop&q=80&w=600',
    tags: ['React', 'TypeScript', 'Node.js', 'USSD', 'M-Pesa API'],
    isFeatured: true,
  },
  {
    id: 'proj-2',
    userId: 'usr-teddy-001',
    title: 'Nairobi Commute - Matatu Fare & Route Tracker',
    description: 'Crowdsourced public transit fare estimator and route optimization engine for commuters across the Nairobi Metropolitan Area.',
    link: 'https://nairobicommute.netlify.app',
    githubLink: 'https://github.com/teddymwangi/nairobi-commute-tracker',
    imageUrl: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&q=80&w=600',
    tags: ['Next.js', 'Tailwind CSS', 'Mapbox GL', 'Supabase'],
    isFeatured: true,
  },
  {
    id: 'proj-3',
    userId: 'usr-teddy-001',
    title: 'AfriPay Invoice & Receipt Generator',
    description: 'Clean invoicing tool built for African freelancers with automatic KRA eTIMS compliant tax calculation and PDF generation.',
    link: 'https://afripay-invoicing.vercel.app',
    githubLink: 'https://github.com/teddymwangi/afripay-invoice',
    imageUrl: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&q=80&w=600',
    tags: ['Vue 3', 'Tailwind', 'PDFKit'],
    isFeatured: false,
  },
];

export const INITIAL_CERTIFICATIONS: Certification[] = [
  {
    id: 'cert-1',
    userId: 'usr-teddy-001',
    name: 'AWS Certified Cloud Practitioner (CLF-C02)',
    issuer: 'Amazon Web Services',
    issueDate: '2025-08-15',
    expiryDate: '2028-08-15',
    credentialUrl: 'https://aws.amazon.com/verification',
  },
  {
    id: 'cert-2',
    userId: 'usr-teddy-001',
    name: 'Meta Front-End Developer Professional Certificate',
    issuer: 'Meta / Coursera',
    issueDate: '2024-11-20',
    credentialUrl: 'https://coursera.org/verify/professional-cert',
  },
];

export const INITIAL_PORTFOLIO: PortfolioConfig = {
  id: 'port-1',
  userId: 'usr-teddy-001',
  slug: 'teddymwangi',
  headline: 'Full-Stack Developer crafting reliable digital products for the African continent',
  bio: 'Hi, I am Teddy! I bridge intuitive frontend experiences with robust backend microservices. I am passionate about leveraging software to solve real problems in logistics, financial inclusion, and education in Kenya.',
  theme: 'modern-navy',
  isPublished: true,
  socialLinks: {
    github: 'https://github.com/teddymwangi',
    linkedin: 'https://linkedin.com/in/teddymwangi',
    twitter: 'https://x.com/teddymwangi_dev',
    website: 'https://careerlaunch.co.ke/u/teddymwangi',
    email: 'teddy.mwangi@uonbi.ac.ke',
  },
  featuredProjectIds: ['proj-1', 'proj-2'],
  viewCount: 342,
  updatedAt: '2026-09-20T10:00:00Z',
};

export const INITIAL_CV: CVDocument = {
  id: 'cv-1',
  userId: 'usr-teddy-001',
  title: 'Teddy Mwangi - Software Engineer CV (2026)',
  templateId: 'modern-navy',
  isDefault: true,
  updatedAt: '2026-09-21T16:00:00Z',
  content: {
    personalInfo: {
      fullName: 'Teddy Mwangi',
      email: 'teddy.mwangi@uonbi.ac.ke',
      phone: '+254 712 345 678',
      location: 'Nairobi, Kenya',
      headline: 'Junior Software Engineer | Full-Stack Developer',
      website: 'careerlaunch.co.ke/u/teddymwangi',
      linkedin: 'linkedin.com/in/teddymwangi',
      github: 'github.com/teddymwangi',
    },
    summary: 'Results-driven Computer Science graduate from University of Nairobi with hands-on experience developing web applications, REST APIs, and payment integrations. Passionate about solving African logistics and fintech challenges using TypeScript, React, Node.js, and cloud services.',
    experience: INITIAL_EXPERIENCE,
    education: INITIAL_EDUCATION,
    skills: INITIAL_SKILLS,
    projects: INITIAL_PROJECTS,
    certifications: INITIAL_CERTIFICATIONS,
    languages: [
      { id: 'lang-1', userId: 'usr-teddy-001', name: 'English', proficiency: 'Fluent' },
      { id: 'lang-2', userId: 'usr-teddy-001', name: 'Swahili', proficiency: 'Native' },
    ],
  },
};

export const INITIAL_LANGUAGES: Language[] = [
  { id: 'lang-1', userId: 'usr-teddy-001', name: 'English', proficiency: 'Fluent' },
  { id: 'lang-2', userId: 'usr-teddy-001', name: 'Swahili', proficiency: 'Native' },
];

export const INITIAL_OPPORTUNITIES: Opportunity[] = [
  {
    id: 'opp-1',
    title: 'Graduate Software Engineer (FinTech & Core Banking)',
    company: 'Safaricom PLC',
    companyLogo: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&q=80&w=120',
    location: 'Westlands, Nairobi',
    country: 'Kenya',
    type: 'Graduate Program',
    workMode: 'Hybrid',
    experienceLevel: 'Entry Level',
    salaryRange: 'KES 140,000 - 180,000 / month',
    currency: 'KES',
    deadline: '2026-10-15',
    description: 'Join Safaricom as part of the 2026 Graduate Technology Intake. You will rotate across M-Pesa Core Engineering, Cloud Infrastructure, and Digital Channels, building resilient systems that power over 30 million active users daily.',
    requirements: [
      'BSc in Computer Science, Software Engineering, or related STEM field (Graduating class 2025/2026)',
      'Working knowledge of at least one programming language: Java, Python, Go, or TypeScript',
      'Understanding of relational databases (PostgreSQL/Oracle) and REST API principles',
      'Keen problem-solving mindset and eagerness to learn cloud-native architectures (Kubernetes/AWS)',
      'Must have completed mandatory university coursework',
    ],
    tags: ['FinTech', 'M-Pesa', 'Java', 'Cloud', 'Graduate Program'],
    applicationUrl: 'https://safaricom.com/careers/graduate-2026',
    contactEmail: 'talent@safaricom.co.ke',
    source: 'Direct Partner',
    status: 'published',
    createdAt: '2026-09-15T09:00:00Z',
  },
  {
    id: 'opp-2',
    title: 'Industrial Attachment: Software Systems & Data',
    company: 'Equity Group Holdings',
    companyLogo: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&q=80&w=120',
    location: 'Equity Centre, Upper Hill, Nairobi',
    country: 'Kenya',
    type: 'Attachment',
    workMode: 'On-site',
    experienceLevel: 'Student/Intern',
    salaryRange: 'KES 35,000 monthly stipend',
    currency: 'KES',
    deadline: '2026-10-05',
    description: 'Accredited industrial attachment for continuing university students fulfilling NITA & university degree requirements. Gain hands-on exposure to digital banking applications, QA automation, and customer experience software.',
    requirements: [
      'Currently enrolled 3rd or 4th year undergraduate student at an accredited Kenyan university',
      'Valid student ID and recommendation letter from university Dean or HOD',
      'Knowledge of web basics (HTML/CSS/JavaScript) or Python',
      'Strong analytical abilities and commitment to data confidentiality',
    ],
    tags: ['Attachment', 'NITA Accredited', 'Banking', 'Python', 'Student'],
    applicationUrl: 'https://equitybankgroup.com/careers/internships',
    contactEmail: 'attachments@equitybank.co.ke',
    source: 'Verified',
    status: 'published',
    createdAt: '2026-09-18T10:30:00Z',
  },
  {
    id: 'opp-3',
    title: 'Junior Frontend Engineer (React / TypeScript)',
    company: 'Andela Africa',
    companyLogo: 'https://images.unsplash.com/photo-1572021335469-31706a17aaef?auto=format&fit=crop&q=80&w=120',
    location: 'Nairobi (Remote Pan-Africa)',
    country: 'Kenya',
    type: 'Job',
    workMode: 'Remote',
    experienceLevel: 'Entry Level',
    salaryRange: '$1,800 - $2,400 / month',
    currency: 'USD',
    deadline: '2026-10-25',
    description: 'Andela is hiring Junior Frontend Engineers to build user interfaces for high-growth tech enterprises across North America and Europe. You will work in distributed agile squads with senior mentors.',
    requirements: [
      '1+ years of practical React and modern JavaScript/TypeScript experience',
      'Proficiency in CSS3, Tailwind CSS, and state management (Zustand, Redux, or TanStack Query)',
      'Comfortable communicating clearly in asynchronous remote environments',
      'Git collaboration and PR review discipline',
    ],
    tags: ['Remote', 'React', 'TypeScript', 'Global Clients', 'USD Salary'],
    applicationUrl: 'https://andela.com/careers/junior-frontend',
    source: 'Andela Partner Network',
    status: 'published',
    createdAt: '2026-09-19T11:00:00Z',
  },
  {
    id: 'opp-4',
    title: 'Cloud Support & DevOps Associate',
    company: 'Microsoft Africa Development Centre (ADC)',
    companyLogo: 'https://images.unsplash.com/photo-1642543492481-44e81e3914a7?auto=format&fit=crop&q=80&w=120',
    location: 'Dunhill Towers, Westlands, Nairobi',
    country: 'Kenya',
    type: 'Job',
    workMode: 'Hybrid',
    experienceLevel: 'Entry Level',
    salaryRange: 'KES 160,000 - 210,000 / month',
    currency: 'KES',
    deadline: '2026-11-01',
    description: 'Empower millions across Africa and worldwide. The Microsoft ADC Nairobi engineering team is looking for enthusiastic early-career engineers to join Azure Cloud Support, optimizing customer telemetry, monitoring, and automated incident resolution.',
    requirements: [
      'Degree in Computer Engineering, Information Technology, or relevant background',
      'Foundational understanding of Linux OS, bash scripting, and TCP/IP networking',
      'Familiarity with cloud platforms (Azure, AWS, or GCP)',
      'Passion for developer advocacy and cloud diagnostics',
    ],
    tags: ['Azure', 'DevOps', 'Cloud', 'Microsoft ADC', 'High Salary'],
    applicationUrl: 'https://careers.microsoft.com/adc-nairobi',
    source: 'Direct Partner',
    status: 'published',
    createdAt: '2026-09-12T08:00:00Z',
  },
  {
    id: 'opp-5',
    title: 'Freelance UI/UX Mobile App Designer (3-Month Gig)',
    company: 'Twiga Foods',
    companyLogo: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&q=80&w=120',
    location: 'Nairobi / Remote',
    country: 'Kenya',
    type: 'Freelance',
    workMode: 'Remote',
    experienceLevel: 'Mid Level',
    salaryRange: 'KES 150,000 fixed milestone budget',
    currency: 'KES',
    deadline: '2026-09-30',
    description: 'Redesigning our vendor inventory ordering app for Android smartphones in low-bandwidth rural environments. Need high-fidelity Figma components, clickable prototypes, and design system tokens.',
    requirements: [
      'Proven portfolio showcasing mobile app UX case studies in Africa',
      'Mastery of Figma, auto-layout, interactive components, and usability testing',
      'Ability to deliver fast iterations based on merchant feedback',
    ],
    tags: ['Figma', 'UI/UX', 'Freelance', 'Mobile', 'Design System'],
    applicationUrl: 'https://twigafoods.com/freelance-design',
    source: 'Verified',
    status: 'published',
    createdAt: '2026-09-20T14:00:00Z',
  },
  {
    id: 'opp-6',
    title: 'Mastercard Foundation Scholars Master\'s Scholarship',
    company: 'Mastercard Foundation & Carnegie Mellon University Africa',
    companyLogo: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&q=80&w=120',
    location: 'Kigali, Rwanda (Full Relocation)',
    country: 'Rwanda',
    type: 'Scholarship',
    workMode: 'On-site',
    experienceLevel: 'Student/Intern',
    salaryRange: '100% Tuition + Living Stipend + Laptop + Flights',
    currency: 'USD',
    deadline: '2026-11-15',
    description: 'Fully funded scholarship for high-achieving African university graduates with demonstrated leadership and commitment to community transformation. Pursue MSc in Information Technology, Electrical & Computer Engineering, or Artificial Intelligence.',
    requirements: [
      'Completed Bachelor degree with Second Class Upper or First Class equivalent',
      'Citizen and resident of an African country',
      'Demonstrated financial need and leadership potential',
      'Strong foundation in mathematics and algorithmic thinking',
    ],
    tags: ['Full Scholarship', 'Masters', 'AI', 'Leadership', 'Kigali'],
    applicationUrl: 'https://www.cmu.edu/africa/admissions/financial-support/mastercard-foundation.html',
    source: 'Partner Foundation',
    status: 'published',
    createdAt: '2026-09-10T12:00:00Z',
  },
  {
    id: 'opp-7',
    title: 'Junior Data Analyst & Business Intelligence Specialist',
    company: 'KCB Bank Kenya',
    companyLogo: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&q=80&w=120',
    location: 'Kencom House, CBD, Nairobi',
    country: 'Kenya',
    type: 'Job',
    workMode: 'Hybrid',
    experienceLevel: 'Entry Level',
    salaryRange: 'KES 110,000 - 135,000 / month',
    currency: 'KES',
    deadline: '2026-10-18',
    description: 'Join the Analytics Centre of Excellence. Responsible for writing SQL queries, building PowerBI executive dashboards, and uncovering micro-lending risk trends across KCB branches in Kenya, Uganda, and Tanzania.',
    requirements: [
      'Degree in Statistics, Actuarial Science, Data Science, or Computer Science',
      'Advanced SQL (subqueries, window functions, indexing)',
      'Experience with Power BI or Tableau visualization tools',
      'Basic knowledge of Python (pandas, matplotlib)',
    ],
    tags: ['SQL', 'Power BI', 'Data Analytics', 'Banking', 'Finance'],
    applicationUrl: 'https://kcbgroup.com/careers/data-analyst',
    source: 'Verified',
    status: 'published',
    createdAt: '2026-09-16T15:00:00Z',
  },
  {
    id: 'opp-8',
    title: 'Mobile App Developer (Flutter / Dart)',
    company: 'Cellulant',
    companyLogo: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&q=80&w=120',
    location: 'Nairobi, Kenya',
    country: 'Kenya',
    type: 'Job',
    workMode: 'Hybrid',
    experienceLevel: 'Entry Level',
    salaryRange: 'KES 130,000 - 165,000 / month',
    currency: 'KES',
    deadline: '2026-10-22',
    description: 'Building next-generation payments checkout interfaces across Tingg payment gateways. Deploy cross-platform iOS and Android apps with smooth offline capabilities.',
    requirements: [
      'Proficiency in Flutter & Dart with at least 1 published mobile app on Google Play or App Store',
      'Experience integrating native device APIs and biometric authentication',
      'Familiarity with state management (BLoC or Provider)',
      'Sound understanding of mobile security standards',
    ],
    tags: ['Flutter', 'Dart', 'Fintech', 'Mobile', 'Tingg'],
    applicationUrl: 'https://cellulant.io/careers/flutter-dev',
    source: 'Direct Partner',
    status: 'published',
    createdAt: '2026-09-17T11:20:00Z',
  },
  {
    id: 'opp-9',
    title: 'Pan-African AI & Agritech Innovation Challenge',
    company: 'Strathmore iLabAfrica & Bill & Melinda Gates Foundation',
    companyLogo: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format&fit=crop&q=80&w=120',
    location: 'Madaraka, Nairobi & Online',
    country: 'Kenya',
    type: 'Competition',
    workMode: 'Hybrid',
    experienceLevel: 'All Levels',
    salaryRange: '$25,000 in Equity-Free Grants & Incubation',
    currency: 'USD',
    deadline: '2026-10-31',
    description: 'Are you building AI, IoT, or drone applications addressing crop disease detection, drought resilience, or market price transparency in Sub-Saharan Africa? Submit your MVP to win seed grants and 6-month mentorship.',
    requirements: [
      'Team of 2 to 4 African university students, graduates, or early founders',
      'Working software prototype or demonstrative algorithm',
      'Clear market validation thesis and implementation timeline',
    ],
    tags: ['Hackathon', 'Grants', 'Agritech', 'AI', 'Strathmore'],
    applicationUrl: 'https://ilabafrica.strathmore.edu/ai-challenge-2026',
    source: 'Verified Partner',
    status: 'published',
    createdAt: '2026-09-14T10:00:00Z',
  }
];

export const INITIAL_APPLICATIONS: JobApplication[] = [
  {
    id: 'app-1',
    userId: 'usr-teddy-001',
    opportunityId: 'opp-4',
    company: 'Microsoft Africa Development Centre (ADC)',
    position: 'Cloud Support & DevOps Associate',
    stage: 'Saved',
    dateApplied: '2026-09-20',
    deadline: '2026-11-01',
    notes: 'Need to review Azure networking architecture concepts and polish my Linux scripting portfolio project before submitting.',
    salary: 'KES 180,000 / mo',
    jobUrl: 'https://careers.microsoft.com/adc-nairobi',
    updatedAt: '2026-09-20T11:00:00Z',
  },
  {
    id: 'app-2',
    userId: 'usr-teddy-001',
    opportunityId: 'opp-3',
    company: 'Andela Africa',
    position: 'Junior Frontend Engineer (React/TypeScript)',
    stage: 'Applied',
    dateApplied: '2026-09-19',
    deadline: '2026-10-25',
    notes: 'Submitted customized CV emphasizing KilimoConnect React/TypeScript code and GitHub PR links. Awaiting coding assessment link.',
    salary: '$2,000 / mo',
    jobUrl: 'https://andela.com/careers/junior-frontend',
    updatedAt: '2026-09-19T14:30:00Z',
  },
  {
    id: 'app-3',
    userId: 'usr-teddy-001',
    opportunityId: 'opp-2',
    company: 'Equity Group Holdings',
    position: 'Industrial Attachment: Software Systems & Data',
    stage: 'Shortlisted',
    dateApplied: '2026-09-10',
    deadline: '2026-10-05',
    notes: 'Received HR email confirming NITA attachment paperwork is approved. Invited to virtual assessment next Tuesday.',
    salary: 'KES 35,000 stipend',
    jobUrl: 'https://equitybankgroup.com/careers/internships',
    updatedAt: '2026-09-17T09:15:00Z',
  },
  {
    id: 'app-4',
    userId: 'usr-teddy-001',
    opportunityId: 'opp-1',
    company: 'Safaricom PLC',
    position: 'Graduate Software Engineer (FinTech & Core Banking)',
    stage: 'Interview',
    dateApplied: '2026-09-05',
    deadline: '2026-10-15',
    notes: 'Stage 2 Technical Panel interview scheduled for October 4th, 10:00 AM EAT. Prepare M-Pesa transaction system design and data structures.',
    salary: 'KES 160,000 / mo',
    interviewDate: '2026-10-04T10:00:00Z',
    jobUrl: 'https://safaricom.com/careers/graduate-2026',
    updatedAt: '2026-09-21T10:00:00Z',
  },
  {
    id: 'app-5',
    userId: 'usr-teddy-001',
    opportunityId: 'opp-8',
    company: 'Cellulant',
    position: 'Mobile App Developer (Flutter / Dart)',
    stage: 'Offer',
    dateApplied: '2026-08-25',
    deadline: '2026-09-28',
    notes: 'Received official offer letter! Base KES 145,000 + comprehensive health insurance and remote stipend. Decision due in 5 days.',
    salary: 'KES 145,000 / mo',
    jobUrl: 'https://cellulant.io/careers/flutter-dev',
    updatedAt: '2026-09-21T15:45:00Z',
  },
  {
    id: 'app-6',
    userId: 'usr-teddy-001',
    company: 'Legacy Bank Ltd',
    position: 'Junior IT Support Clerk',
    stage: 'Rejected',
    dateApplied: '2026-07-15',
    notes: 'Role had higher focus on hardware printer maintenance rather than software development. Good decision to redirect to developer positions.',
    salary: 'KES 60,000 / mo',
    updatedAt: '2026-08-01T12:00:00Z',
  },
];

export const INITIAL_SAVED_OPP_IDS: string[] = ['opp-1', 'opp-3', 'opp-6'];

export const INITIAL_RESOURCES: CareerResource[] = [
  {
    id: 'res-1',
    title: 'The Complete Guide to Securing an Industrial Attachment in Kenya (NITA Accredited)',
    slug: 'securing-industrial-attachment-kenya',
    category: 'Industrial Attachment',
    summary: 'Everything Kenyan university and TVET students need to know: NITA clearance, mandatory insurance, finding corporate openings, and converting an attachment into a full-time role.',
    readTime: '6 min read',
    author: 'Teddy Mwangi & CareerLaunch Team',
    tags: ['NITA', 'Attachment', 'University', 'Kenya', 'Internship'],
    isFeatured: true,
    publishedAt: '2026-08-15',
    content: `Securing an industrial attachment in Kenya is a mandatory academic milestone for university students pursuing STEM, business, and humanities disciplines. Beyond fulfilling graduation requirements, it is often your first real foot in the corporate door.

### 1. Understanding NITA Requirements
The National Industrial Training Authority (NITA) regulates industrial attachments.
Ensure you obtain:
- An official letter of recommendation from your Dean or Departmental Attachment Coordinator
- Valid Student Personal Accident Insurance cover (available affordably via university partnerships)
- A certified copy of your National ID and KRA PIN certificate.

### 2. Timeline and When to Apply
Top multinationals like Safaricom, KenGen, KPLC, Equity Bank, and BAT publish their attachment intake calls 3 to 5 months in advance:
- **May - August Intake**: Applications close between January and March.
- **September - December Intake**: Applications close between May and July.

### 3. Making Your Application Stand Out
Don't send generic letters. Research the exact division you want to join. Highlight campus projects, hackathon achievements, and relevant coursework. Keep your CV concise at 1 to 2 pages.`
  },
  {
    id: 'res-2',
    title: 'Acing Technical Interviews at Safaricom, Equity and Top African Tech Hubs',
    slug: 'acing-tech-interviews-africa',
    category: 'Interview Prep',
    summary: 'A deep-dive into coding tests, system design for high-concurrency mobile money applications, and behavioral STAR techniques that African hiring managers look for.',
    readTime: '8 min read',
    author: 'Emmanuel Kiprono, Senior Tech Recruiter',
    tags: ['Interview', 'FinTech', 'Safaricom', 'System Design', 'Algorithms'],
    isFeatured: true,
    publishedAt: '2026-09-02',
    content: `Tech hiring across Nairobi, Lagos, and Kigali has evolved significantly. Top companies no longer just test syntax—they test whether you can design systems that handle unpredictable network latency and millions of daily transactions.

### Key Focus Areas:
1. **Data Structures & Algorithms**: Arrays, Hash Maps, Binary Trees, and Big-O notation.
2. **System Design**: How would you design a rate limiter for M-Pesa Daraja API?
3. **Behavioral Questions**: Using the STAR method (Situation, Task, Action, Result) to explain how you navigated production bugs or campus deadlines.`
  },
  {
    id: 'res-3',
    title: 'How to Build an Irresistible Tech CV as a University Graduate with Zero Experience',
    slug: 'tech-cv-guide-graduates-kenya',
    category: 'CV & Portfolio',
    summary: 'Transform academic projects, capstones, and self-directed learning into high-impact CV bullet points that bypass ATS filters and impress engineering leads.',
    readTime: '5 min read',
    author: 'Amina Wanjiku',
    tags: ['CV Builder', 'Resume', 'Graduates', 'ATS Friendly'],
    isFeatured: true,
    publishedAt: '2026-09-10',
    content: `When you don't have 5 years of corporate experience, your CV currency is **Proof of Work**. 
    
Include:
- Real links to working deployed apps (e.g. Vercel, Netlify, Render)
- GitHub repositories with clear READMEs, architecture diagrams, and commit history
- Quantified accomplishments: "Built an e-commerce prototype that reduced checkout steps from 6 to 3".`
  },
  {
    id: 'res-4',
    title: 'Winning Mastercard Foundation, Chevening & DAAD Scholarships from East Africa',
    slug: 'winning-mastercard-chevening-scholarships',
    category: 'Scholarships',
    summary: 'Step-by-step strategies for writing compelling personal essays, securing credible academic referee letters, and articulating your post-study African development vision.',
    readTime: '10 min read',
    author: 'Dr. Wanjiku Githinji, Global Scholars Mentor',
    tags: ['Scholarships', 'Mastercard Foundation', 'Chevening', 'Postgraduate'],
    isFeatured: false,
    publishedAt: '2026-08-28',
    content: `Prestigious international scholarships prioritize leadership and a demonstrable vision for giving back to your home community.

### 3 Pillars of a Winning Essay:
1. **The Catalyst**: What specific problem in your country or community ignited your passion?
2. **The Academic Vehicle**: Why is this specific degree and institution the exact catalyst you need?
3. **The Ripple Effect**: Exactly how will you implement this knowledge when you return to Africa?`
  },
  {
    id: 'res-5',
    title: 'Freelancing on Upwork & Toptal from Nairobi: Dollar Invoicing, M-Pesa and Taxes',
    slug: 'freelancing-kenya-guide',
    category: 'Freelancing',
    summary: 'Navigating international remote contracts from East Africa: receiving USD funds via Payoneer, Wise, or direct M-Pesa, managing KRA taxes, and pricing your services.',
    readTime: '7 min read',
    author: 'Brian Ochieng, Full-Stack Consultant',
    tags: ['Freelance', 'Remote Work', 'M-Pesa', 'Taxes', 'USD Income'],
    isFeatured: false,
    publishedAt: '2026-09-12',
    content: `Remote freelancing allows African developers and designers to earn competitive international rates while residing locally.
    
Learn how to optimize your client profile, negotiate hourly vs milestone deliverables, and use proper international invoicing.`
  }
];

export const INITIAL_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-1',
    userId: 'usr-teddy-001',
    title: 'Interview Upcoming! 🗓️',
    message: 'Your Technical Interview with Safaricom PLC is scheduled for October 4th at 10:00 AM EAT.',
    type: 'application',
    isRead: false,
    actionUrl: '/applications',
    createdAt: '2026-09-21T10:05:00Z',
  },
  {
    id: 'notif-2',
    userId: 'usr-teddy-001',
    title: 'New Matching Opportunity 🚀',
    message: 'A new role matching your React & TypeScript skills was posted: "Junior Frontend Engineer at Andela Africa".',
    type: 'opportunity',
    isRead: false,
    actionUrl: '/opportunities',
    createdAt: '2026-09-19T11:05:00Z',
  },
  {
    id: 'notif-3',
    userId: 'usr-teddy-001',
    title: 'Profile Strength Recommendation',
    message: 'Adding a link to your deployed projects will increase your profile strength to 90% and boost employer views.',
    type: 'info',
    isRead: true,
    actionUrl: '/profile',
    createdAt: '2026-09-18T16:00:00Z',
  },
];

export const INITIAL_SKILL_GAPS: RoleSkillGap[] = [
  {
    targetRole: 'Junior Full-Stack Engineer at Safaricom PLC',
    companyTarget: 'Safaricom PLC',
    matchScore: 78,
    matchedSkills: ['React & Next.js', 'TypeScript', 'Node.js & Express', 'RESTful API Design', 'Git & GitHub'],
    missingSkills: [
      { name: 'Docker & Container Basics', importance: 'High', recommendedResource: 'Docker Fundamentals for African Developers' },
      { name: 'Redis Caching & Queue Processing', importance: 'Medium', recommendedResource: 'Building High-Concurrency Microservices' },
      { name: 'CI/CD Pipelines (GitHub Actions)', importance: 'Medium', recommendedResource: 'Automating Deployments' },
    ],
  },
  {
    targetRole: 'Junior Frontend Engineer at Andela',
    companyTarget: 'Andela',
    matchScore: 88,
    matchedSkills: ['React & Next.js', 'TypeScript', 'Git & GitHub', 'RESTful API Design'],
    missingSkills: [
      { name: 'Unit Testing with Vitest & React Testing Library', importance: 'High', recommendedResource: 'Testing Production React Apps' },
      { name: 'GraphQL & Apollo Client', importance: 'Nice to have', recommendedResource: 'GraphQL Deep Dive' },
    ],
  },
];

export const INITIAL_ADMIN_STATS: AdminStats = {
  totalUsers: 14850,
  activeOpportunities: 342,
  applicationsTracked: 28910,
  totalPortfolios: 6140,
  activeSubscriptions: 1820,
  weeklyGrowthRate: 14.8,
  categoryDistribution: [
    { category: 'Software Engineering', count: 4200 },
    { category: 'Data & AI', count: 2800 },
    { category: 'Product Design & UI/UX', count: 2100 },
    { category: 'Finance & Banking', count: 1950 },
    { category: 'Digital Marketing & Content', count: 1600 },
    { category: 'Green Tech & Agritech', count: 1200 },
    { category: 'Engineering & Construction', count: 1000 },
  ],
  regionalDistribution: [
    { region: 'Kenya (Nairobi, Mombasa, Kisumu, Eldoret)', count: 8900 },
    { region: 'Nigeria (Lagos, Abuja, Port Harcourt)', count: 2400 },
    { region: 'Rwanda (Kigali)', count: 1350 },
    { region: 'Ghana (Accra, Kumasi)', count: 1100 },
    { region: 'Uganda & Tanzania', count: 1100 },
  ],
};

